language: python

env:
  - PYTORCH=http://download.pytorch.org/whl/cpu/torch-0.4.1-cp36-cp36m-linux_x86_64.whl

python:
  - "3.6"

sudo: required

jobs:
  include:
    - stage: doc
      script:
        - make install-docs-requirements
        - make docs

install:
  - pip3 install --quiet ${PYTORCH} torchvision
  - python setup.py develop
  - make install-tests-requirements

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
